# SPDX-License-Identifier: MIT-0
---
# Installer les bibliothèques nécessaires pour gérer MySQL/MariaDB
- name: Installer les bibliothèques Python pour Ansible et MySQL (Debian/Ubuntu)
  apt:
    name:
      - python3-pymysql
      - python3-mysql.connector
    state: present
  when: ansible_os_family == "Debian"

- name: Installer les bibliothèques Python pour Ansible et MySQL (RedHat/Rocky)
  dnf:
    name:
      - python3-PyMySQL
    state: present
  when: ansible_os_family == "RedHat"
# 1. Mettre à jour les paquets des systèmes
- name: Mettre à jour les paquets (RedHat/Rocky)
  when: ansible_os_family == "RedHat"
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Installer apt-utils et mettre à jour les paquets (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    name: apt-utils
    state: present
    update_cache: yes

# 2. Installer les paquets nécessaires
- name: Installer les paquets nécessaires (RedHat/Rocky)
  when: ansible_os_family == "RedHat"
  dnf:
    name:
      - httpd
      - php
      - php-mysqlnd
      - mariadb-server
      - wget
      - unzip
    state: present

- name: Installer les paquets nécessaires (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
      - mariadb-server
      - wget
      - unzip
    state: present


# 3. Nettoyer et résoudre les installations interrompues
- name: Résoudre les installations interrompues (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  command: apt-get install --fix-broken -y

# 4. Activer et démarrer les services Apache
- name: Activer et démarrer Apache
  service:
    name: "{{ apache_service_name }}"
    state: started
    enabled: yes

# 5. Supprimer la page par défaut d'Apache
- name: Supprimer la page par défaut d'Apache
  file:
    path: /var/www/html/index.html
    state: absent

# 6. Activer et démarrer les services MariaDB
- name: Vérifier l'installation de MariaDB
  stat:
    path: /usr/bin/mysql
  register: mariadb_binary

- name: Démarrer MariaDB seulement si installé
  service:
    name: "{{ mariadb_service_name }}"
    state: started
    enabled: yes
  when: mariadb_binary.stat.exists

- name: Tester la connexion MariaDB
  shell: |
    mysql -uroot -pexamplerootPW -e "SELECT VERSION();"
  ignore_errors: yes


# 7. Configuration de MariaDB
- name: Sécuriser MariaDB - Modifier le mot de passe root
  mysql_user:
    name: root
    host: localhost
    password: examplerootPW
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Supprimer les utilisateurs anonymes de MariaDB
  mysql_user:
    name: ''
    state: absent
    login_user: root
    login_password: examplerootPW

- name: Supprimer la base de test de MariaDB
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: examplerootPW

- name: Rafraîchir les privilèges de MariaDB
  command: mysql -uroot -pexamplerootPW -e "FLUSH PRIVILEGES"

- name: Créer la base de données WordPress
  mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: examplerootPW

- name: Créer un utilisateur MariaDB pour WordPress
  mysql_user:
    name: example
    password: examplePW
    host: localhost
    priv: 'wordpress.*:ALL'
    state: present
    login_user: root
    login_password: examplerootPW

# 8. Télécharger et déployer WordPress
- name: Télécharger WordPress
  get_url:
    url: https://wordpress.org/latest.zip
    dest: /tmp/latest.zip

- name: Décompresser WordPress
  unarchive:
    src: /tmp/latest.zip
    dest: /tmp
    remote_src: yes

- name: Copier WordPress dans le dossier /var/www/html/
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    remote_src: yes

# 9. Ajuster les permissions des fichiers WordPress
- name: Changer les permissions du dossier web (RedHat/Rocky)
  when: ansible_os_family == "RedHat"
  command: chown -R apache:apache /var/www/html/

- name: Changer les permissions du dossier web (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  command: chown -R www-data:www-data /var/www/html/

