#SPDX-License-Identifier: MIT-0
---
# handlers file for ansible-role-deploy-wordpress

- name: Redémarrer Apache
  service:
    name: "{{ apache_service_name }}"
    state: restarted

- name: Redémarrer MariaDB
  service:
    name: "{{ mariadb_service_name }}"
    state: restarted
