#SPDX-License-Identifier: MIT-0
---
# handlers file for ansible-role-deploy-wordpress

- name: restart apache
  service:
    name: "{{ apache_package }}"
    state: restarted

- name: reload apache
  service:
    name: "{{ apache_package }}"
    state: reloaded
